outputDir: /etc/nginx/sites-available/
rootDir: /var/www/gallery
host: example.test
path: '' # name
port: default # 80 for HTTP, 443 for HTTPS
thumbnails: false # or string with cache directory
ssl: false
  #redirectFromHttpPort: 80 # false
  #sslCertificate:
  #sslCertificateKey:
  #letsEncryptSnippet: false
httpAuth: false
  #file:
  #token: false

#css - sass
#js - modules rollup

#photo
#+360
#video+vtt
#other

#download <a download="" ...>
#show
#share
#exif-map

#favicon